#!/usr/bin/env python3
"""
HaackLang compiler CLI wrapper.
Allows running as: haackc file.haack
"""

import sys
import os

# Add src directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from haackc.main import main

if __name__ == '__main__':
    main()
